### ISSUE TITLE
自动模式增加倒数日、时间模式改进

### ISSUE THREAD

**Issue by C21H21NO2S** [OpaqueGlass/progressBarT-sywidget#12]
同时显示能看到deadline和进展，希望可以考虑，谢谢。

另外一些建议可以看看。

1. 时间进度条有颜色变化的话就锦上添花了，样式建议：
    - 前景颜色（黄 橙 红），按剩余天数变化，背景颜色（绿）；
    - 前后标时间，中间显示剩余天数或超多天数。

2. 开始时间希望可用有一个插入当前时间的按钮。

**Comment by OpaqueGlass** [comment]
感谢提议：
1. 不太清楚“同时显示”是什么，可否给个示例？如果是同时显示两个进度条的话暂时不考虑，麻烦插入两个挂件；我先想到的是将时间和任务进度合并到一个进度条里显示，这个我会尝试一下；
2. 颜色按照任务进度变化，这个在现有的垃圾代码下比较难弄，还需考虑一下；另外需要明确，具体分几段、何时切换颜色；
4. 前后标时间是标在哪里？目前时间模式有天数标注（就是进度条下面那个D-xx）；
5. 下个版本加入插入当前时间；

任务拆分：（如果完成了在此更新）
- [x] （开始）插入当前时间、（结束）插入下个月、下周，或接入其他日期选择控件；
- [x] 自动模式下，设置结束时间时，在下方展示截止时间信息；
- [x] 更改天数标注文案，并支持config.js配置；
- [x] 自动模式，设置结束时间时，文字提示统一移动至进度条下方居中显示；
- [x] 仅时间剩余天数提示根据剩余天数（而不是进度比例）切换颜色，颜色和切换时机可通过`config.js`配置（不支持挂件内直接设定）；
- [x] 时间模式左上方显示标题，右上方显示进度、天数，左右两侧显示开始、结束时间；
- [x] 如果同时设定开始时间与结束时间，则按照剩余时间比例切换颜色；
- [ ] ~~设置时间时，手动模式显示剩余天数（类似自动模式）；~~ 暂不推进
- [ ] ~~自动模式下，设置时间时，在主进度条上叠层显示时间进度~~ 暂不推进；
- [x] 时间模式预设：天进度、周进度、月进度、年进度；

**Comment by C21H21NO2S** [comment]
> 感谢提议：
> 
> 1. 不太清楚“同时显示”是什么，可否给个示例？如果是同时显示两个进度条的话暂时不考虑，麻烦插入两个挂件；我先想到的是将时间和任务进度合并到一个进度条里显示，这个我会尝试一下；
> 2. 颜色按照任务进度变化，这个在现有的垃圾代码下比较难弄，还需考虑一下；另外需要明确，具体分几段、何时切换颜色；
> 3. 前后标时间是标在哪里？目前时间模式有天数标注（就是进度条下面那个D-xx）；
> 4. 下个版本加入插入当前时间；
> 
> 任务进展：（如果完成了在此更新）
> 
> * [ ]  （开始）插入当前时间、（结束）插入下个月、下周，或接入其他日期选择控件；
> * [ ]

嗯嗯，
1.  对于“同时显示“，我想的是用在有子任务的TODO中，看到时间剩余还能看到TODO进度，其实我没想怎么展示，不过现在只有时间进度条也能用；
2. 功能现在已经够用，其他的都是些交互的建议，你随意。进度条前后显示对应的时间，中间显示”剩9天“ ”超9天“，而不是”D-9“ ”+9“。
❤

**Comment by OpaqueGlass** [comment]
只是在任务进度条下面显示还有几天是吗？我明白了。
另外，暂时不会在进度条那一行加其他内容，剩余几天可能还是放在进度条下面。

**Comment by OpaqueGlass** [comment]
在任务进度条下显示截止日期、还有多少天已经初步完成，如果可以，麻烦测试一下，谢谢。[v0.1.3-beta2](https://github.com/OpaqueGlass/progressBarT-sywidget/releases/tag/v0.1.3-beta2)
![image](https://user-images.githubusercontent.com/52985952/227533677-716bbdec-b3ec-4153-bdb7-580bd18ff9f0.png)

---

时间模式我可能会改成下面这样（下图只是个示例，还没开始改代码），能再给点建议吗？
![image](https://user-images.githubusercontent.com/52985952/227533895-d1138955-45a6-4736-a3e1-75c364fc39c7.png)

**Comment by holduan** [comment]
> 

nice， 我试了，改进了很多，感觉现在的自动模式就够实用了。有些小地方可以改改，你可以看看：
1. 提示语在进度条底下居中比较好，所有重要信息都集中一处，并简化，例如：自动模式——完成80% 剩1天 2023/3/25
2. 提示语简化：剩1天，截止日，超1天
3. 还是奢望一下，时间提示语有更多的颜色变化，哈哈哈

以上，感谢大佬

**Comment by C21H21NO2S** [comment]
> 在任务进度条下显示截止日期、还有多少天已经初步完成，如果可以，麻烦测试一下，谢谢。[v0.1.3-beta2](https://github.com/OpaqueGlass/progressBarT-sywidget/releases/tag/v0.1.3-beta2) ![image](https://user-images.githubusercontent.com/52985952/227533677-716bbdec-b3ec-4153-bdb7-580bd18ff9f0.png)
> 
> 时间模式我可能会改成下面这样（下图只是个示例，还没开始改代码），能再给点建议吗？ ![image](https://user-images.githubusercontent.com/52985952/227533895-d1138955-45a6-4736-a3e1-75c364fc39c7.png)

nice， 我试了，改进了很多，感觉现在的自动模式就够实用了。有些小地方可以改改，你可以看看：

1. 提示语在进度条底下居中比较好，所有重要信息都集中一处，并简化，例如：自动模式——完成80% 剩1天 2023/3/25
2. 提示语简化：剩1天，截止日，超1天
3. 还是奢望一下，时间提示语有更多的颜色变化，哈哈哈

以上，感谢大佬

**Comment by OpaqueGlass** [comment]
目前改成这个样子了，颜色变化基于剩余天数（不是进度比例）；
![image](https://user-images.githubusercontent.com/52985952/229291883-4d0cbd63-551e-49c3-9f39-d415b3f12e79.png)

能给一些颜色方面的建议吗？（具体采用什么颜色、还剩几天的时候换颜色）

**Comment by C21H21NO2S** [comment]
> 目前改成这个样子了，颜色变化基于剩余天数（不是进度比例）； ![image](https://user-images.githubusercontent.com/52985952/229291883-4d0cbd63-551e-49c3-9f39-d415b3f12e79.png)
> 
> 能给一些颜色方面的建议吗？（具体采用什么颜色、还剩几天的时候换颜色）

色卡变化，相对于按天数决定，我感觉由剩余时间百分比决定更合理一些。五个色卡的话，可以考虑 “红” “橙” “黄” “黄绿” “青绿”（“黄绿” “青绿”直接用“绿” “蓝”也可以），比例可以是 10% 20% 20% 20% 30%

另外，自动模式下，进度条右边的数值我感觉可以去掉。日期由 2023/4/6 改成 2023.04.06 会没那么抢眼

**Comment by OpaqueGlass** [comment]
[新的测试版已发布](https://github.com/OpaqueGlass/progressBarT-sywidget/releases/tag/v0.1.3-beta3)，麻烦测试一下，谢谢！


1. 颜色已修改，如果还有更好的颜色建议，麻烦直接给颜色值（十六进制或者rgb）；
2. 倒数日颜色和切换时机只能在`config.js`中通过改文件修改；
3. 进度条右侧的内容和显示设置挂钩，如果突然没有会比较突兀，还打算不显示的话，将config.js中的hideRightPercentage: false改为true；
4. 日期可以通过增加`dateFormat` `dateFormat_simp`属性修改；
![image](https://user-images.githubusercontent.com/52985952/231119159-7b2b46fe-351f-4f08-a749-512751d83f87.png)

**Comment by C21H21NO2S** [comment]
> [新的测试版已发布](https://github.com/OpaqueGlass/progressBarT-sywidget/releases/tag/v0.1.3-beta3)，麻烦测试一下，谢谢！
> 
> 1. 颜色已修改，如果还有更好的颜色建议，麻烦直接给颜色值（十六进制或者rgb）；
> 2. 倒数日颜色和切换时机只能在`config.js`中通过改文件修改；
> 3. 进度条右侧的内容和显示设置挂钩，如果突然没有会比较突兀，还打算不显示的话，将config.js中的hideRightPercentage: false改为true；
> 4. 日期可以通过增加`dateFormat` `dateFormat_simp`属性修改；
>    ![image](https://user-images.githubusercontent.com/52985952/231119159-7b2b46fe-351f-4f08-a749-512751d83f87.png)

嗯嗯，感谢，我觉得现在已经完全够用了。再请教一下，请问进度条和提示词的间距怎么调整啊。

**Comment by OpaqueGlass** [comment]
> 请问进度条和提示词的间距怎么调整啊。

修改挂件目录/static/progressbar.css
在最后加入：
```
#outerInfos {
    margin-top: 10px;
}
```
只是预览效果的话，ctrl+shift+I 打开开发者工具，然后：
![image](https://user-images.githubusercontent.com/52985952/231177617-4f7f53b5-6ba5-435e-a789-9090d41784b1.png)
