### ISSUE TITLE
手动模式拖动或者点击进度条无效

### ISSUE THREAD

**Issue by dacenss** [OpaqueGlass/progressBarT-sywidget#13]
另外貌似不该出现时间模式下的设置选项
![image](https://github.com/OpaqueGlass/progressBarT-sywidget/assets/125509413/c1ec1445-626c-4cc9-8bb7-f2661c15adf1)

**Comment by OpaqueGlass** [comment]
感谢反馈，明早修哈，晚安

**Comment by OpaqueGlass** [comment]
已修复，稍后在集市更新。
> 另外貌似不该出现时间模式下的设置选项

这个……没有设计隐藏无关的设置项，所有模式都显示所有设置项。
