### ISSUE TITLE
【Bug】列表内的进度条在SQL查询块，反链面板内展示会显示设置，原文档内不会

### ISSUE THREAD

**Issue by C21H21NO2S** [OpaqueGlass/progressBarT-sywidget#14]
如题
![QQ图片20240229172852](https://github.com/OpaqueGlass/progressBarT-sywidget/assets/80377040/81b59fee-2434-48ce-97be-c1cc737b3815)

**Comment by OpaqueGlass** [comment]
暂时没有复现，麻烦说一下：
1. 原文中挂件位于哪里；
2. 跟踪的任务列表块位于哪里；

**Comment by OpaqueGlass** [comment]
哦哦，复现了，感谢反馈

**Comment by OpaqueGlass** [comment]
麻烦试一下这个版本：[progress-dev.zip](https://github.com/OpaqueGlass/progressBarT-sywidget/files/14455303/progress-dev.zip)

**Comment by C21H21NO2S** [comment]
这个可以，之前的问题解决了

OpaqueGlass ***@***.***> 于 2024年3月1日周五 09:28写道：

**Comment by OpaqueGlass** [comment]
此版本已经发布在集市，issue先关闭了哈。（不必回复）

**Comment by OpaqueGlass** [comment]
新增了一个按钮获取并填充下方任务列表的id，在你这种使用情况下或许能方便一些
![这里应该有图片](https://github.com/user-attachments/assets/953aea4c-23a3-485c-a705-fb57b7994b2c)
