### ISSUE TITLE
计算剩余天数时可以排除周末和节假日吗

### ISSUE THREAD

**Issue by zhangjunquan** [OpaqueGlass/progressBarT-sywidget#18]

**Comment by OpaqueGlass** [comment]
可以，之后再做

---

参考json结果：https://raw.githubusercontent.com/lanceliao/china-holiday-calender/master/holidayAPI.json

转换为下述形式追加保存到 `storage`
```json
{
"holiday": ["2024-01-01"],
"workday": ["2024-02-04"]
}

```

**Comment by OpaqueGlass** [comment]
来测试一下？ https://github.com/OpaqueGlass/progressBarT-sywidget/releases/tag/v0.2.0-rc1
