### ISSUE TITLE
子项包括无序列表时，错误计算任务个数

### ISSUE THREAD

**Issue by lentikr** [OpaqueGlass/progressBarT-sywidget#5]
当前版本对子任务的统计并没有判断块类型。
可能导致的问题：待办项的子项为无序列表（如记录任务思路）时，即便勾选所有的待办事项，进度也达不到100%。
![image](https://user-images.githubusercontent.com/95539012/194747444-649c61e1-d018-4571-ba86-24a11e7a3884.png)
解决方案：添加对待办项子项块类型的判断，仅子项为待办块时才看作是子任务。

**Comment by OpaqueGlass** [comment]
感谢反馈，下个版本修复。如果可以，请下载此版本测试，谢谢。
[progressBarT-dev-fix#5.zip](https://github.com/OpaqueGlass/progressBarT-sywidget/files/9741746/progressBarT-dev-fix.5.zip)

**Comment by lentikr** [comment]
> 感谢反馈，下个版本修复。如果可以，请下载此版本测试，谢谢。 [progressBarT-dev-fix#5.zip](https://github.com/OpaqueGlass/progressBarT-sywidget/files/9741746/progressBarT-dev-fix.5.zip)

这个版本可以了的，谢谢大佬(๑•̀ㅂ•́)و✧

**Comment by OpaqueGlass** [comment]
ok，谢谢反馈😊
