### ISSUE TITLE
时间模式无效

### ISSUE THREAD

**Issue by 2016201256** [OpaqueGlass/progressBarT-sywidget#6]
输入了开始时间和结束时间之后仍然提示未设置任务列表块, 而不是按照时间显示进度.
![image](https://user-images.githubusercontent.com/58763608/197384271-3a490025-4afe-4969-9832-3360d0d3a0bb.png)

**Comment by OpaqueGlass** [comment]
嗯....或许我该考虑一下在设置页面加个当前模式的显示；

另外问一下，有没有觉得时间模式只输入日期的情况下，00:00:00显得有点多余？我想着下一版本时间为0时就不显示时间了，如下图，或者有什么其他建议吗？
![image](https://user-images.githubusercontent.com/52985952/197388995-0e4a0d8e-271e-4cbc-b8d6-7a8a6df01892.png)
